### ISSUE TITLE
Feature Request: Select File 

### ISSUE THREAD

**Issue by JDiaz11** [bartreardon/swiftDialog-scripts#9]
I just discovered **swiftDialog** and I am honestly as thrilled as the proverbial _kid in candy store_!! Thank you for this awesome app!
I was wondering if you might consider adding a **Select File** button feature? (similar to AppleScript's "choose file") Thank you.

**Comment by bartreardon** [comment]
I know you closed this already but you can do this with the `fileselect` option on a textfield.

e.g. `dialog --textfield "Select a file",fileselect`

I need to update the docs and help - I notice this isn't documented anywhere

**Comment by bartreardon** [comment]
oh wait - it is documented https://github.com/bartreardon/swiftDialog/wiki/Textfields#fileselect-and-filetype
